asciidoctor/asciidoctor.org

docs/_includes/block.adoc, docs/_includes/ex-quote.adoc, docs/asciidoc-syntax-quick-reference.adoc, docs/asciidoc-writers-guide.adoc
This mostly a starting point for discussion—I'm not quite sure if I've put things in the right place, or worded these things clearly.
See https://github.com/asciidoctor/asciidoctor/issues/1254
=> Add documentation for citetitle substitutions.

docs/_includes/glossary.adoc, docs/_includes/multi-special-ex.adoc, docs/user-manual.adoc
As per [issue #45](/asciidoctor/asciidoctor-fopub/issues/45)
=> Adding info on Glossary to User Manual 

docs/asciidoctor-diagram.adoc
Hello! I see that someone copypasted the line of text without changing the topic. This is a fix for it.
=> Fixed overlooked change when copypasting

docs/convert-asciidoc-to-pdf.adoc
The wrong script is mentioned.
=> wrong script fix

_layouts/base.html.slim
Update the Twitter URL, as the existing one does not direct to the account page.
=> Update Twitter URL

docs/_includes/block.adoc, docs/_includes/ex-section.adoc, docs/_includes/ex-src.adoc, docs/_includes/ex-xref.adoc, docs/_includes/image.adoc, docs/_includes/sections.adoc, docs/_includes/src.adoc, docs/_includes/xref-anchor.adoc, docs/_includes/xref.adoc, docs/asciidoc-writers-guide.adoc, docs/user-manual.adoc
=> Document "cross references" and "xreflabel"

docs/_includes/docinfo.adoc
This is an update in relation to issue 424
=> updated doco for footer docinfo

docs/user-manual.adoc
First of all, apologies for the two micro commits here instead of just one. Still getting used to working with Append, but I'll get there. 
You'll note that some Sections still are declared as Section Pending. These were parent sections with child section nodes and I felt they should not have a tracker. I can easily remedy that.
=> Issue 432 Sections Pending

docs/user-manual.adoc
Added Guard/Live doc viewer terse info and linked to project readme.
=> Issue #450 - Guard/Live viewer info

index.adoc
About the code page change that is required when working in windows command line
=> Provide a tip for installing asciidoc on Windows

docs/_includes/ex-xref.adoc, docs/_includes/xref-anchor.adoc
Discussion on the Mailing List:
http://discuss.asciidoctor.org/anchor-link-to-ordered-list-item-td4256.html
=> Add anchor definition in list items

docs/_includes/sum-table.adoc
For some reason the comment in column 4 is coming out monospaced.
=> Document fix for https://github.com/asciidoctor/asciidoctor/issues/1140

docs/_includes/multiple-include.adoc, docs/user-manual.adoc
re https://github.com/asciidoctor/asciidoctor/issues/1696
=> Document use of variable IDs for multiple inclusion

docs/editing-asciidoc-with-live-preview.adoc
=> Fix typo ican -> can

docs/_includes/include-directive.adoc, docs/_includes/include-lines-tags.adoc, docs/user-manual.adoc
For review please.
The only problem that I know of is that the footnote link goes to the wrong place, and I am not sure why.
Slightly worried that I have gone from too "reference" to too "tutorial"!
=> Re issue #506 includes

.gitignore
This should not harm anyone and makes it more comfortable for me to use my favorite ide for text editing.
=> Add `.idea` Directory to `.gitignore` File

_layouts/base.html.slim, stylesheets/styles.scss
=> Resolves #543, remove G+ button from the menu

docs/asciidoctorj.adoc
Taken from AsciiDoctorJ's readme, which was two versions ahead already.
Fixes asciidoctor/asciidoctorj#445.
=> Updated documentation for AsciiDoctorJ

docs/_includes/footnote.adoc
The PR is self explaining I guess.
cheers,
René
=> Fix typo in footnote section of userguide

docs/_includes/ex-header-attr.adoc, docs/_includes/ex-section.adoc, docs/asciidoc-syntax-quick-reference.adoc
Some of the results did not match the expected results for the shown code.
=> Quickref fixes

docs/_includes/formatting-marks.adoc
See https://github.com/asciidoctor/asciidoctor-intellij-plugin/pull/128#issuecomment-239701862
=> added a colon the the list of characters requiring an unconstrained formatting

docs/_includes/table-formatting.adoc
Fixes issue 426 table autowidth
=> Resovles #426 document the autowidth option for tables

docs/user-manual.adoc
=> Resolves #630 variables

docs/_includes/ex-o-list.adoc, docs/_includes/o-list.adoc
Resolves #602 reversed
New reversed option for ordered lists in html and pdf
=> Resolves #602 reversed

docs/_includes/messages.adoc, docs/user-manual.adoc
Please don't accept this! I just want to check the layout with you before spending time populating it.
=> Resolves #204 error message list

docs/_includes/docinfo.adoc, docs/user-manual.adoc
=> resolves #604 document the new docinfo configuration

news/asciidoctor-js-1-5-0-released.adoc
Even tough this news is quite old, it is still well ranked by search engines (for "asciidoctor bower"), so this fix might help some copy/paste beginners like me.
=> Fix bower-based example, from the 2014-08-23 news

docs/editing-asciidoc-with-live-preview.adoc
It was using the French page before
=> Updated the firefox addon URL to english page

docs/asciidoctorj.adoc
Fixed a title and unified capsing
=> Copy and Paste error for Include Processor

docs/_includes/attr-doc.adoc, docs/_includes/subs-apply.adoc, docs/_includes/ts-url-format.adoc, docs/asciidoc-syntax-quick-reference.adoc
=> Fixed URL to Passthrough Macros

docs/_includes/attrs-builtin.adoc, docs/_includes/attrs-env.adoc
Resolves #672 document list numbers
=> Resolves #672 document list numbers

docs/_includes/ex-table-data.adoc, docs/_includes/sum-table.adoc, docs/_includes/table-data.adoc
Also reworked CSV linking to RFC 4180 and made data format more explicit.
=> Resolves #684 tsv

docs/_includes/formatting-marks.adoc
This is the last remnant of my changes to fix #686 😩
=> Clarify explanation for unconstrained example

docs/index.adoc
=> Update API docs link for Ruby and Javadoc

docs/_includes/subs-attr.adoc, docs/_includes/subs-macro.adoc, docs/_includes/subs-post.adoc, docs/_includes/subs-quote.adoc, docs/_includes/subs-repl.adoc
Rename the first row, column 1, of each of these tables, from "Attribute value" to "Attribute Entry Value".
(Cf. #727 re the row's semantics.)
=> In 40.2-6, rename Row 1 of "Elements subject to"

docs/asciidoctor-maven-plugin.adoc
particularly https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/322
=> update page to match plugin's README

docs/install-asciidoctor-osx.adoc
Ref https://github.com/asciidoctor/asciidoctor/pull/2469.
I also removed/updated some heavily outdated information.
=> Update Homebrew installation procedure for macOS

docs/asciidoctor-revealjs.adoc
See https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v1.1.0
=> Refer to new release of asciidoctor-revealjs 1.1.0

docs/asciidoctor-revealjs.adoc
See https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v1.1.1
=> asciidoctor-revealjs 1.1.1 is out!

_config/site.yml, docs/_includes/project-author.adoc, docs/_includes/project-lic.adoc, docs/index.adoc, docs/user-manual.adoc, humans.txt, index.adoc
- update Asciidoctor description in site.yml
- update copyright in user manual
- add header attributes to user manual
- update Asciidoctor metadata description
=> minor docs and site upkeep

docs/_includes/command-line-usage.adoc, docs/_includes/ex-desc.adoc, docs/_includes/ex-keyword.adoc, docs/_includes/ex-listing.adoc
We could define an attribute but I didn't know where to define it 😉
=> Use the latest version of Asciidoctor in the examples

docs/extensions.adoc
The extension is well documented on GitHub. Based on the [discussion on Twitter](https://twitter.com/bmuschko/status/1075398807829983233), other users seem to be interested in the functionality.
=> List extension for rendering tabbed code blocks

docs/_includes/text-mono.adoc
Small typo corrections for monospace documentation.
=> interpret spelling and gets correction

docs/extensions.adoc
I've included a list with some extensions I developped 
Most of them are in an stable version except *quiz* that it's in an `experimental` state
=> include puravida software extensions

docs/extensions.adoc
Add Calendar block as another available extension
=> add calendar extension

docs/asciidoctor-maven-plugin.adoc
=> Improve docs

docs/_includes/attr-doc.adoc
=> Improve attr-doc.adoc

docs/extensions.adoc
Some corrections for grammar and misspellings.
=> Update extensions.adoc for typos and grammar

docs/asciidoctor-diagram.adoc
It should fetch the latest version of the README
=> Update Asciidoctor Diagram version

docs/_includes/messages.adoc
aligning doc to output of code
=> update message in doc to conform with how it looks on screen

docs/asciidoc-writers-guide.adoc
=> Fix misspelling in asciidoc-writers-guilde.adoc

_ext/routers/asciidoctor.js.js
=> resolves #996 redirect /docs/asciidoctor.js to docs.asciidoctor.org

.awestruct_ignore, LICENSE, NOTICE.adoc, _layouts/base.html.slim, docs/LICENSE
* add LICENSE file to root to cover all source code
* add LICENSE file to docs folder to cover all documentation content
* add NOTICE.adoc file to outline declared licenses
=> clarify licenses for this repository
