docs/_includes/para-line-break.adoc

A liitle typo in the Writer's Guide

Fix a typo 'throughtout->throughout'

---

javascripts/view-result.js

Hi! This pull request aims to refactor  `view-result.js` and include these commits.
- Fix accidental global variables https://github.com/azu/asciidoctor.org/commit/5cae5c66b7fc8a144fbb72d780c957b6ff3ad055
- Improve creating a link node (reduce waste) https://github.com/azu/asciidoctor.org/commit/47ace5fb39ab1dfad2b55a70dd523572cd059d53
- Remove unnecessary `$.proxy` and refactor `toggle_result_block` method https://github.com/azu/asciidoctor.org/commit/c45136122b491a1a7aaeb4dffbcf0acdef40ce80
`view-result.js` is used in http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/ .

Refactoring JavaScript

---

docs/asciidoc-syntax-quick-reference.adoc

(very) minor change
Section titles are wrongly called headers instead of headings. This change will remove a potential ambiguity between "document header" and "headers", and make it consistent with the rest of the text (ex. in the Markdown Compatibility section where the term headings is being used).

Section Titles (Headers -> Headings)

---

docs/editing-asciidoc-with-live-preview.adoc

Version 0.3.0 is available with Asciidoctor 1.5.2.js and Opal 0.6.3

Update the download link of the Firefox addon

---

docs/_includes/sum-table.adoc
docs/_includes/table-formatting.adoc

All values for grid appear functional: all, cols, rows, none.

Table attribute 'grid' works just fine

---

docs/editing-asciidoc-with-live-preview.adoc

* `rb-inotify` is Linux only. Guard now uses `listen` gem which will works cross platform
* It is recommended to use Bundler through `bundle` binary instead of `bundler`
* When using bundler, the Guardfile needs `Bundler.require(:default)`

Fix Guard and Bundler usage

---

docs/_includes/appendix.adoc
docs/_includes/ex-appendix.adoc
docs/user-manual.adoc

With the information found [in the mailing list](http://discuss.asciidoctor.org/Appendix-sectnums-td706.html) and in [asciidoctor/issues/683](https://github.com/asciidoctor/asciidoctor/issues/683), I was able to propose some text for the `Appendix` section of the [User Manual](asciidoctor.org/docs/user-manual/).
Current text is:
NOTE: Section pending

Add Appendix section in user-manual

---

docs/_includes/ex-o-list.adoc
docs/_includes/o-list.adoc

As discussed on the [mailing list](http://discuss.asciidoctor.org/Number-lists-give-warnings-td2526.html), ordered list using number needs to be sequential.
This pull request adds more information in the ordered list section.

Precision for ordered list

---

docs/_includes/ex-include.adoc
docs/_includes/include-lines-tags.adoc

Related discussion on the [mailing list](http://discuss.asciidoctor.org/Include-directive-by-line-range-with-multiple-ranges-not-working-tp3056.html)

Fix include with multiple ranges example

---

docs/_includes/ex-url.adoc
docs/_includes/ex-xref.adoc
docs/_includes/url-relative.adoc
docs/_includes/xref-relative.adoc
docs/asciidoc-writers-guide.adoc

As discussed on the mailing list: [Link to an other document ](http://discuss.asciidoctor.org/Link-to-an-other-document-td2857.html) the section [Links to relative files](http://asciidoctor.org/docs/asciidoc-writers-guide/#links-to-relative-files) of the "AsciiDoc Writer’s Guide" needs to be updated.

Change Links to relative files

---

docs/extensions.adoc
docs/index.adoc

A followup to this [post](http://discuss.asciidoctor.org/MonoTree-extension-tp2903p2946.html) on asciidoctor forum. I doubt that this change can be considered "complete", but it's still something to start from.
I wasn't able to check if awestruct processes this change correctly - spent several hours trying to configure environment on Windows 7 (different combinations of ruby versions, build tools, etc.), but failed.

Add section with Asciidoctor extensions

---

docs/_includes/sections.adoc

The #asciidoctor user manual is broken: 
* 18.3. Links
* 18.4. Anchors
* 18.5. Numbering
* 18.6. Links
* 18.7. Anchors
* 18.8. Numbering
* …
Bug introduced with 00d4ea2b0b13ed78efb92e013b3c02a62a731572

Fix autoid closing tag in sections.adoc

---

docs/_includes/install-upgrade-asciidoctor.adoc

I installed Asciidoctor the other day, and it was `sudo dnf install asciidoctor`.
I love how it pulls in all the Ruby dependencies you'd need anyhow to run the PDF converter: super sweet!

Updated for dnf vs yum

---

index.adoc

Fix typo on homepage

---

docs/_includes/apply-theme.adoc
docs/_includes/u-list.adoc

I was reading the nice website documentation and found a couple minor misspellings. So I fixed them, _separately_.

Spelling fixes in the website

---

docs/_includes/apply-theme.adoc
docs/produce-custom-themes-using-asciidoctor-stylesheet-factory.adoc

This message: "The copycss attribute, which would copy a custom stylesheet when a document is rendered, is broken. Watch Issue #300 for updates." appears on the Custom Themes part of the documentation. According to https://github.com/asciidoctor/asciidoctor/issues/300, this is no longer the case.

remove 'caution: copycss is broken' from docs

---

docs/_includes/formatting-marks.adoc
docs/user-manual.adoc

* declare a constrained and unconstrained formatting marks section in the user guide.
Added a formatting marks include containing the following info:
- constrained formatting explanation
- unconstrained formatting explanation
- why unconstrained formatting is required.

resolves #64 with the following improvements:

---

docs/asciidoc-recommended-practices.adoc

I think we should make this clear and I see `adoc` as the clear winner.

Recommend using `adoc` as file extension

---

docs/_includes/attr-builtin.adoc

Please check:
* skip-front-matter refers to front-matter, so added front-matter to metadata for want of anywhere else
* changed default for reffileprefix to empty because it seems like it should be
* couldn't find anywhere to link man-linkstyle to

resolves issue #480 more attributes

---

docs/editing-asciidoc-with-live-preview.adoc

I've just evaluated AsciiDocFx, Sublime Text Editor 3 and Visual Studio Code for Asciidoctor editing. I came out slightly disappointed with them. The IntelliJ plugin, however, works very well, and it deserves mention here.

contents: mention IntelliJ IDEA Asciidoc plugin

---

docs/_includes/block.adoc

It looks like the intended statement was "invalid sidebar block" as the block uses the * character.

Fix typo in block.adoc

---

docs/_includes/listing.adoc

See http://asciidoctor.org/docs/user-manual/#listing-blocks, example 3 for the erroneous result.

Fixed result of listing block example showing wrong result.

---

docs/install-asciidoctor-macosx.adoc

MacPorts is one of the two widely used package managers for open source software on OS X (Brew being the other one). This change adds instructions for installing Asciidoctor by means of MacPorts.

Add MacPorts instructions to install Asciidoctor

---

docs/what-is-asciidoc.adoc

neo4j/neo4j#8235 moved the manual out of the tree, presumably to
maintain it in the separate neo4j/neo4j-documentation project. That
project has no `master` branch so point to the `3.1` branch instead.

Fix broken link to Neo4j manual

---

docs/_includes/callout-xml.adoc

Note that use of font icons is required for XML callouts to ensure that they will not be selectable and provide the rendering described in the doc.
The use of font icons is covered in the next section of the documentation, and this led me to believe it wasn't necessary to achieve the rendering described (but that font icons were an alternative mechanism of achieving the same rendering). Admittedly this confusion largely arose because I'm a complete newbie but for me at least the documentation appeared to imply that font icons weren't a requirement to achieve the "light number in dark circle" rendering for callouts, so I believe other newbies might make a similar mistake. Therefore I've suggested a tiny clarification to the documentation on XML callouts.

Note use of font icons for non-selectable callouts

---

docs/_includes/exten-intro.adoc

The reference to the status of Extensions in v0.1.4 is probably outdated. Any new information about extensions and their use should be added, and other references throughout the user manual should probably also be updated. Those are in example text, so they would not be substantive changes.

Remove warning about extensions for v0.1.4

---

docs/_includes/ex-table.adoc
docs/_includes/table.adoc

As [discussed](http://discuss.asciidoctor.org/Table-amp-column-example-from-the-doc-is-not-working-td5129.html) on the mailing list, I have fixed the example "Table with rolename".
Because at this point of the docs, the `cols` attribute is not explained, I have changed the example with the rows defined on the same line (as in the previous example).
In `ex-table.adoc` file, I have moved the `tag::base[]` example (near to the other `base` examples). This snippet is used a lot in the `table-col.adoc` File.

Fix the table example with rolename

---

README.adoc

This PR changes the link to the image used by the build status badge in the README to use shiny SVG.
_Thank you for this project!_

README: Use SVG build badge icon

---

docs/asciidoc-syntax-quick-reference.adoc

The link in the TIP from [**Inline image with positioning role**](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#images) don't work correctly.

fix uri-image-attrs link

---

docs/asciidoctor-diagram.adoc

Update readme to include the latest readme for asciidoctor-diagram. I was missing the diagram attributes table recently and think it should be accessible from a more popular location ;-)

Update revnumber to include the latest readme

---

README.adoc

Make it explicite that older Awestruc is used.

README: link to external frameworks used

---

docs/asciidoc-writers-guide.adoc

Correct `An optional revision, a date and an option remark` to `An optional revision, a date and an optional remark`, option -> optional.

Spelling/grammar: "An optional revision, a date and an option remark"

---

docs/_includes/table-data.adoc

Just a few things that I noticed while checking out the recent changes (701b7dc7e168549e25482e58f923169de6e9b892) in docs. No changes in meaning, just grammar, and such.

A few minor fixes to chapter 26.11 Delimiter-Separated Values.

---

docs/asciidoctor-revealjs.adoc

I forgot to do that in the past releases. I'm adding this to my release documentation.

Linking to asciidoctor-reveal.js v1.0.4

---

docs/_includes/stem.adoc

Though it seems intuitive, putting `++++` inline in normal text doesn't work. What's coming through from it is `<code></code>`.
I'm guessing it is treated as a "single plus" passthrough macro, within another -- and, perhaps in keeping with sec. 40.5, the inner passthrough is processed (passing an empty value), and then the outer one (doing likewise!).

Apply style attribute to ++++ being taken as macro

---

docs/_includes/subs-symbol-repl.adoc

I don't see the point in having backslash escapes inside a literal column. 
I'm guessing that the escapes had already been entered, and later the author of the table decided to make columns 2 and 3 literal-format. But, the escapes "escaped" eviction (even tho they had become redundant).

Remove redundant escape '\'s in literal columns

---

docs/_includes/ex-manpage.adoc

I'm not sure how formatting is done in a man page -- I've written exactly zero of them.
However, I'm guessing that the literal styling this AsciiDoc source is shown in, makes that \ escape of the copyright symbol-code redundant.

Remove redundant \ escape in a literal-style block

---

docs/_includes/text-quote-apos.adoc

At the end of this section on Quotation Marks and Apostrophes (22.2 on the website), there is a link, broken, to the Passthroughs section (43 on the website). It's broken only because it has '#passthru', while the ID of sec. 43 is '#passthroughs'. A quick realignment of the spelling, and  we're "in business" ;)

Correct typo in cross-ref. to Passthroughs section

---

docs/_includes/subs-post.adoc

The table in view is entitled, "Elements subject to post replacements text substitution". Its section, 40.6, is entitled, "Post Replacements". Please bear with me as I try to explain the problem as quickly as I can... I'm really just trying to check my understanding of how AsciiDoctor works (which, when it seems not to comport with something in the manual, concerns me!!).
So yes--I must admit, I'm a bit unsure of the exact semantics of this "Attribute value" row, in such tables (in Secs. 40.1-40.6). However, logic seems to constrain a reasonable interpreter thus: 
This row's presence here would make no sense, really, if the row intended to refer either to
1) "Named attributes" (which, according to Sec. 13.5.2, have their own substitution rules, dependent on use of single or double …

Emend "Attribute value" row in sec. 40.6 table

---

docs/_includes/attr-doc.adoc

The section challenged the reader by, first, starting with a paragraph that's only about the "header" substitution group (no mention of attribute entries, which is what the section is allegedly about). Then it follows this paragraph with several that speak only of attribute-entry values (no mention of header substitution!). In vain does the reader scan the text for a link connecting paragraph 1 with the rest.
The minimal missing connection is the one in this text, which we have added to paragraph 2: [The header substitution group] "is applied also to attribute entries' values, whether those entries are in the header or elsewhere in the document".
Our argument for this addition is:
1) At least in our experience and tests of AsciiDoctor, attribute-entries' values do indeed behave as if …

Add crucial, missing sentence(s) to Sec. 13.4.1

---

docs/_includes/subs.adoc

One paragraph in Sec. 40 describes the "Header" substitution group. PR #730 has now made important clarifications about that substitution group, in Sec. 13.4.1. This PR applies a minimal update to the description of it in Sec. 40, using some of the new language of Sec. 13.4.1. 
The sentence I've added here about inline pass macros should especially be scrutinized (it might need massaging ;)

Update description of "Header" subs-group per #730

---

docs/_includes/subs-macro.adoc
docs/_includes/subs-post.adoc

In Sections 40.5 (Macros substitutions) and 40.6 (Post Replacements substitutions), change the 2d column values, from check-marks to "X"s, in the "Header" rows in the "Elements subject to [whichever type of] text substitution" tables.
This is related to the repairs discussed in PRs #729 and #730.

Emend "Header" rows, Elements tables, secs. 40.5-6

---

docs/_includes/attr-doc.adoc

With the aid of Dan's explanation at PR #731, I took a wild stab at broadening Sec. 13.4.1's explanation of how the inline pass macro affects the substitutions happening to an attribute-entry value. 
Emendations (or rejections) expected--and more than welcome!

Explain how pass-macro "preprocesses" attr values

---

docs/_includes/formatting-marks.adoc

Where the User Manual gives us the conditions under which we need to use unconstrained (rather than constrained)  quotes (Sec. 12.3), it lists a couple of marks which, only when they appear directly before the opening quote, require it:
- Is there a colon or semi-colon directly before the starting formatting mark?
But in my experimentation, it seems that a closing curly bracket causes the same necessity. 
This is the case, for example, when you have an attribute reference immediately before the starting formatting mark and you are using quote-substitution before attribute-ref-substitution--as in the normal substitution ordering.
Am I by any chance right about this?? :D

Add another case requiring unconstrained quotes

---

docs/_includes/apply-theme.adoc

Correct me if I'm wrong, but in this final Sec.-76 code-example, the first directory-move must be to the directory (/mydocuments) which is the parent of the directory (/mynesteddocuments) that contains the current file (c.adoc), since said parent is the directory that contains the directory you're trying to reference (/mystylesheets). So, the single-dot should be a double-dot, in the filepath.

Emend :stylesdir: to navigate via parent directory

---

docs/_includes/xrefstyle.adoc

This fixes a spelling in the section about `xrefstyle`.

Fix misspelling in xrefstyle section

---

docs/index.adoc

The link is 404 in the live site

Fix LICENSE link

---

docs/_includes/attrs-builtin.adoc

The **Allowed values** field for the `copycss` attribute erroneously says *empty*. Instead, it should say that the value needs to specify the location of the stylesheet (provided we don't want the `stylesheet` attribute to resolve relative to the base directory. This PR fixes that.
See also https://github.com/asciidoctor/asciidoctor/issues/300#issuecomment-26478893.

Fix allowed value for :copycss:

---

Rakefile
_config/site.yml
_ext/awestruct_ext.rb
_ext/pipeline.rb
_layouts/base.html.slim

- set awestruct profile to match Netlify context
- add deploy-preview profile to site config
- set -u flag using value of DEPLOY_PRIME_URL env var if context is not production
- simplify script to redirect from asciidoctor.netlify.com to asciidoctor.org
- add production? helper method to Engine
- disable disqus unless profile is production

configure settings for Netlify deploy preview

---

docs/_includes/url.adoc

When describing the hide-uri-scheme attribute the documentation uses an https url, but then says note the absence of http in the url. Given it is https I expect this was an oversight.
I'm sorry if there are contribution guidelines I'm supposed to follow I couldn't find any.

Update reference to http to be https

---

docs/_includes/exten-tree.adoc

I don't think having a |document| parameter is correct here, for the code-block passed to Asciidoctor::Extensions.register ...?? (It didn't work when I tried it, anyway--but I'm not sure why! :)

Emend demo code for registering treeprocessor

---

docs/user-manual.adoc

Put the material in the (logical) order it appeared in the README.adoc in the Stylesheet Factory GitHub page (https://github.com/asciidoctor/asciidoctor-stylesheet-factory). After all, you can't know even what folders the current section 72 is talking about, till you've started Sec. 73. It wasn't until I read the GitHub page that I could see that the User Manual had somehow gotten these sections out of the didactically logical order that appears on GitHub. There might be a few tweaks that could help, in addition to this transposition of the sections; but just the transposition, with nothing else done, would make the material vastly more intelligible--IMHO.

transpose sections 72 and 73

---

docs/user-manual.adoc

When the IRC link was changed to Gitter, the `uri-irc` reference was left in the note, resulting in the markup rendering verbatim.

Fix attribute reference in preface note

---

docs/_includes/ex-dlist.adoc

A `second term` has been mistakenly spelled `section term`.
(Else the french translation on which I'm working on is 50% complete, regarding the asciidoc-syntax-quick-reference… it's a slow work, but I'm not alone to work on)

fix typo in docs/_includes/ex-dlist.adoc

---

docs/_includes/attrs-charref.adoc

Else… I'm proofreading our complete french translation for the asciidoc-syntax-quick-reference.fr.adoc.

Another typo (attrs_charref)

---

docs/_includes/html-styles.adoc

Add missing space in User Manual `html-styles.adoc`, which prevents
correct page generation at
<http://asciidoctor.org/docs/user-manual/#styling-the-html-with-css>.

Fix trivial syntax error in User Manual

---

docs/_includes/templates-api.adoc
docs/user-manual.adoc

These examples would have helped me a few weeks ago, I thought we should add them to the docs.
The test suite has almost no examples but asciidoctor-backends is like gold for someone wanting to use templates.

Add htmlbook and link the asciidoctor-backends repo to template examples

---

docs/migrating-from-msword.adoc

Related to https://github.com/asciidoctor/asciidoctor.org/issues/542
This PR:
- Removes the `--normalize` flag, no longer necessary
- Updates tested on software
- Added information about links compatibility
- Added link to @Mogztter GitHub on mention
- Fixed a couple of typos
- Removes unused attribute `uri-ant`

Updated migrating-from-msword.adoc to pandoc 2.0

---

news/making-the-switch-to-semver.adoc

Add a post to the blog announcing the switch to Semantic Versioning in Asciidoctor. This immediately affects Asciidoctor, AsciidoctorJ, and Asciidoctor.js, though other projects will likely follow.

add post announcing the switch to semver

---

docs/asciidoctor-revealjs.adoc

Took the liberty to handle the FIXME. The link works so it looks ok.

Update website ref: Asciidoctor-reveal.js 2.0.0 is released

---

docs/_includes/src.adoc

The link to prettify highlight in _[§46.2. Available Source Highlighters]_ is obsolete, prettify has now officially moved to GitHub.
Old link:
- https://code.google.com/archive/p/google-code-prettify/
New link:
- https://github.com/google/code-prettify
[§46.2. Available Source Highlighters]: https://asciidoctor.org/docs/user-manual/#available-source-highlighters

Fix Prettify Link

---

docs/_includes/ex-o-list.adoc
docs/asciidoc-vs-markdown.adoc

* https://asciidoctor-docs.netlify.com/asciidoctor/1.5/project/asciidoc-vs-markdown/
- First noticed here
- Submitted PR: https://github.com/asciidoctor/asciidoctor/pull/3125
---
Essentially, keep the examples consistent with the rest of the examples in the user manual.

fix(lists): remove leading space from list examples in user manual

---

docs/asciidoc-recommended-practices.adoc

Aligned recommended-practices for multi-line attribute with reference doc found here: https://asciidoctor.org/docs/user-manual/#splitting-attribute-values-over-multiple-lines
PS: Please double check, if introduced link to user manual is correctly leading to attribute splitting section.

Align multi-line attribute info

---

_layouts/base.html.slim

This change removes the link from the template. 
I was unable to test this locally due to general problems with rake in my installation. 
I hope Netlify will provide a preview.

google+ no longer active

---

docs/_includes/attrs-env.adoc

The footnote links were missing in some places in the
`docs/_includes/attrs-env.adoc` file.

Add missing footnote links in attr-envs.adoc

---

docs/asciidoc-recommended-practices.adoc

* most changes are self-explanatory
* I changed `Meta` to `Metadata` to match the sample document that follows it
* I changed `//` to `//-` because that's what the [User Manual](https://asciidoctor.org/docs/user-manual/#unordered-lists) uses: "the - text in the line comment indicates the line serves as an “end of list” marker"

Editorial changes

---

docs/_includes/imagesdir.adoc

To enhance readability of the user guide, I deleted the repeated article 'the' and fixed the phrasal verb 'add ... to ...'.

fix word repetition in imagesdir.adoc

---

docs/_includes/callout-xml.adoc

Hi Dan, thanks for merging [PR#910](https://github.com/asciidoctor/asciidoctor.org/pull/910).
To enhance readability of the user guide, I also deleted the repeated article 'the' in the Callouts chapter.

fix word repetition in callout-xml.adoc

---

docs/_includes/language-support.adoc

Hi Dan, thanks again for merging [PR#911](https://github.com/asciidoctor/asciidoctor.org/pull/911). Glad to hear you love these :-)
To enhance readability of the user guide, I also replaced the article 'the' by the word 'to' in the Using Asciidoctor with Other Languages chapter.

fix word repetition in language-support.adoc

---

docs/_includes/ex-callout.adoc

I tried using callouts in HTML source code, but the syntax is a little different, as I found out in this issue: asciidoctor/asciidoctor#1608. I thought this could be documented

Update documentation for callouts in HTML code

---

docs/_includes/require-asciidoctor.adoc

See <https://github.com/asciidoctor/asciidoctor.org/issues/923>.

Fix link to Ruby API documentation

---

docs/asciidoctor-revealjs.adoc

Also, official name is now Asciidoctor reveal.js (reveal.js not capitalized, like upstream). Made a change to keywords to reflect that.

Asciidoctor reveal.js version 3.1.0 released

---

docs/asciidoctor-revealjs.adoc

4.0.0 was missing the npm package by mistake so I had to do a 4.0.1 because apparently you can't replace an unpublished npm package even 5 minutes after the initial upload

Asciidoctor reveal.js version bump

---

.gitignore

It would ease the live of people who use rbenv to manage their Ruby installations, if files used by rbenv as `.ruby-version` would be ignored by Git.

Git should ignore files used by rbenv

---

docs/asciidoc-syntax-quick-reference.adoc

Fix typo: remaining of columns -> remaining columns.

Fix "remaining of columns" typo in syntax ref

---

docs/asciidoc-vs-markdown.adoc

`link:#_usage[Usage]` is AsciiDoc syntax.

Fix markdown syntax for cross referencing

---

docs/_includes/xref-source-to-source.adoc

Similar to a6fae10141625782d0a2dda8f4af3419187de09f. The correct `outfilesuffix` setting has been [implemented](https://gitlab.com/gitlab-org/gitlab/-/commit/9a450aedc2c81f8ce17e4c9b4238c58edbef8269) in GitLab for over two years now.

add note that outfilesuffix defaults to source file extension on GitLab too

---

docs/asciidoctor-gradle-plugin.adoc

As of this writing 3.2.0 is the latest version of the plugin.
https://github.com/asciidoctor/asciidoctor-gradle-plugin/releases
This PR was formerly part of #950 .
cc @ysb33r

Update Gradle plugin reference to 3.2.0

---

Gemfile

Awestruct 0.6.1 is the first version supporting Asiidoctor 2 and brings a couple more changes:
https://github.com/awestruct/awestruct/releases
(Formerly part of #950 )

Update Awestruct to 0.6.1

---

docs/_includes/uri-include.adoc

As per my tests, and the rest of the docs, when run from the CLI, AsciiDoctor runs in UNSAFE mode. 
https://asciidoctor.org/docs/user-manual/#set-the-safe-mode-in-the-cli
"When Asciidoctor is invoked via the CLI, the safe mode is set to UNSAFE by default." This is indeed correct as per my tests.

Fix typo SAFE --> UNSAFE

---

docs/editing-asciidoc-with-live-preview.adoc

Add Visual Studio Code as being an editor with Asciidoc preview capability.
The language has been kept the same as for Brackets.
Nothing more needed than signposting that VSCode is suitable.

feat(editing-asciidoc-with-live-preview.): Add vscode

---

docs/_includes/ex-ulist.adoc

This is only to fix small typo in Edgar Allan Poe's name in AsciiDoctor unordered list example.

Fix typo in unordered list example

---

docs/_includes/ulist-complex.adoc
docs/asciidoc-writers-guide.adoc

These are only small fixes of minor typos that I've found in the text while studying it. :-)

Fix small typos in the text of Writer's Guide

---

docs/extensions.adoc

This extension adds a block that you can use to create Pathfinder 2E statblocks. More info about the extension can be found at https://bosco.srht.site/asciidoctor-p2e.html and https://using.tech/posts/p2e/.

List asciidoctor-p2e extension

---

_ext/routers/asciidoctor-maven-plugin.js
_ext/routers/hack-asciidoctor-maven-plugin.js

Adds redirections for */docs/asciidoctor-maven-plugin* and */docs/hack-asciidoctor-maven-plugin* to the new docs site (docs.asciidoctor.org/).
Note that:
* Not all links have a direct translation because some sections were removed. For example, the attributes and "building".
* This depends on this PR https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/509. @mojavelinux I recall docs need to be rebuild after the merge?

Redirect maven docs to docs.aciidoctor.org

---

docs/_includes/asciidoc-article-template.adoc

If I read [the documentation about the revision line](https://docs.asciidoctor.org/asciidoc/latest/document/revision-line/#when-can-i-use-the-revision-line) correctly, then the revision's remark should be separated from the date by a colon, and not a comma, as is done in the template.
This change would fix this mistake.

Separate document revision remark with a colon

---

docs/asciidoc-writers-guide.adoc

GitHub is not the only place where AsciiDoc is supported
Codeberg supports it, with the same level of accuracy as GitHub on rendering (though `include::[]` are merely a link and that links sometimes 404 at this time if in a subfolder linking relatively) where block titles look a bit weird and admonitions are in an ugly table. GitLab is supported as well--and that support is more robust (with `include::[]`) and the styling generally nicer to top it off. This merge request looks to highlight this fact and have people consider using an open-source or open-core code forge over a proprietary, closed source one.
`Codeberg, GitHub, or GitLab` is ordered alphabetically.

Add Codeberg + GitLab to the 'Where' section

---

docs/asciidoc-writers-guide.adoc

In the previous commit, I forgot to add the usually unnecessary `link:`
directive prefix, but butted up against a slash, this does not render a
link.

Fix / + link in Writer’s Guide

---

docs/what-is-asciidoc.adoc

Update footnote stating AsciiDoc is over a decade old; AsciiDoc is now over 2 decades old.

Update AsciiDoc Age Footnote.

---

Rakefile
_config/supporters.yml
_tasks/supporters.rake
supporters.html.slim

I can't for the life of me get awestruct to work on my Windows machine. The code itself was pretty easy but I wasted about half a day trying to set up the ruby env to see if my changes would actually look right but I failed. I will try this again tonight when I get home to my trusty Linux machines. They'll comply ... or else.
I tried adapting everything as simply as possible with as little changes as I could make. Please have a look.

Retrieve Tiered List of Supporters from OpenCollective API
